version: "3.8"

services:
  foquz_nginx:
    container_name: foquz_nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3200:3200"
    depends_on:
      - foquz_php_fpm
    restart: unless-stopped

  foquz_php_fpm:
    platform: linux/x86_64
    container_name: foquz_php_fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - foquz_postgres

  foquz_php_cli:
    platform: linux/x86_64
    container_name: foquz_php_cli
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - foquz_postgres

  foquz_postgres:
    container_name: foquz_postgres
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "db"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    external: true
    name: foquz_network

volumes:
  postgres-db-data:
