#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/config/bootstrap.php';

use yii\console\Application;
use Dotenv\Dotenv;

(Dotenv::createUnsafeImmutable(
        dirname(__DIR__, 1),
    ['.env'],
    false
))->load();

$config = require __DIR__ . '/config/console.php';

$exitCode = (new Application($config))->run();
exit($exitCode);
